/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_X.h"
#include "PWM_Y.h"
#include "timer_clock.h"
#include "Timer.h"
#include "ResistiveTouch.h"
#include "isr_Timer.h"
#include "Out_X_aliases.h"
#include "Out_X.h"
#include "Out_Y_aliases.h"
#include "Out_Y.h"
#include "ResistiveTouch_AMux.h"
#include "ResistiveTouch_xm_aliases.h"
#include "ResistiveTouch_xm.h"
#include "ResistiveTouch_xp_aliases.h"
#include "ResistiveTouch_xp.h"
#include "ResistiveTouch_ym_aliases.h"
#include "ResistiveTouch_ym.h"
#include "ResistiveTouch_yp_aliases.h"
#include "ResistiveTouch_yp.h"
#include "ResistiveTouch_ADC.h"
#include "ResistiveTouch_ADC_AMux.h"
#include "ResistiveTouch_ADC_Ext_CP_Clk.h"
#include "ResistiveTouch_ADC_IRQ.h"
#include "ResistiveTouch_ADC_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

